"""add_session_logs_table

Revision ID: eedb69ca31e0
Revises: 117702df230f
Create Date: 2026-06-21 19:01:39.326401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedb69ca31e0'
down_revision: Union[str, Sequence[str], None] = '117702df230f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('session_type', sa.String(length=100), nullable=True),
    sa.Column('discussed_items', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_logs_id'), 'session_logs', ['id'], unique=False)
    op.create_index(op.f('ix_session_logs_user_id'), 'session_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_logs_user_id'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_id'), table_name='session_logs')
    op.drop_table('session_logs')
    # ### end Alembic commands ###
